version: "3.9"

services:
  pdf_processor:
    platform: linux/amd64        # ✅ Moved here
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adobe_pdf_processor
    volumes:
      - ./sample-dataset:/app/sample-dataset:ro
      - ./output:/app/output
    network_mode: "none"
    stdin_open: true
    tty: true
